# Generated by Django 5.0 on 2024-01-20 21:29

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_confirmtoken_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=200, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
