# Generated by Django 5.0 on 2024-01-20 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='confirmtoken',
            managers=[
            ],
        ),
    ]
