# Generated by Django 5.0 on 2024-01-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_confirmtoken_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmtoken',
            name='key',
            field=models.CharField(max_length=35),
        ),
    ]
