# Generated by Django 5.0 on 2024-01-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_productinfo_external_id_alter_productinfo_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
