# Generated by Django 5.0 on 2024-02-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_remove_orderitem_product_remove_orderitem_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_sum',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
