# Generated by Django 5.0 on 2024-02-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_orderitem_total_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='total_sum',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
