# Generated by Django 5.0 on 2024-02-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_orderitem_total_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total_sum',
        ),
        migrations.AddField(
            model_name='order',
            name='total_sum',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
