# Generated by Django 5.0 on 2024-02-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_remove_orderitem_total_sum_order_total_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In_progress'), ('completed', 'Completed'), ('rejected', 'Rejected')]),
        ),
    ]
